// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MultiTouchSupport","status":true,"description":"Allow Multi Touch screen to function properly.","parameters":{"Flick Length":"20","Long Touch Length":"90","MultiTouch Threshold":"5","Swipe Threshold":"10","Debug Mode":"true"}}
];
